//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beyaz")]
        public string BackGroundThemeColor {
            get {
                return ((string)(this["BackGroundThemeColor"]));
            }
            set {
                this["BackGroundThemeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("555")]
        public string ButtonBackGroundColor1nd {
            get {
                return ((string)(this["ButtonBackGroundColor1nd"]));
            }
            set {
                this["ButtonBackGroundColor1nd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E7E5DF")]
        public string ButtonBackGroundColor2nd {
            get {
                return ((string)(this["ButtonBackGroundColor2nd"]));
            }
            set {
                this["ButtonBackGroundColor2nd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#77CDBC")]
        public string ButtonForeGroundColor1nd {
            get {
                return ((string)(this["ButtonForeGroundColor1nd"]));
            }
            set {
                this["ButtonForeGroundColor1nd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E7BB41")]
        public string ButtonForeGroundColor2nd {
            get {
                return ((string)(this["ButtonForeGroundColor2nd"]));
            }
            set {
                this["ButtonForeGroundColor2nd"] = value;
            }
        }
    }
}
